### ISSUE TITLE
cpp version

### ISSUE THREAD

**Issue by MoffKalast** [choprahetarth/Sparkfun_VR_IMU_UART_ROS#1]
If anyone's looking for it, there is a slightly more "proper" implementation of this driver by chip robotics https://github.com/chiprobotics/chip_imu_driver

Unfortunately both of these are UART-RVC instead of UART-SHTP, and do not provide nor mag data nor the onboard fused quaternion, and as such barely scratches the usability of the sensor.

This may sound slightly passive aggressive, but I'm mainly triggered by the line in the readme:

> TODO Filter the data incoming from the IMU by applying a Kalman/Complimentary Filter.

No amount of filtering will solve the issue that you're reading the wrong data. The sensor already has top tier filtering that it uses internally with perfect data compared to most other IMUs, it's fully capable of providing a stable continuous orientation. There's just no way to access it properly over serial. Hillcrest seems to have designed an in house serial protocol so convoluted and complex that nobody actually knows how to write a driver for it. Instead of writing one themselves, they made a whole new simplified serial mode that drops most of the functionality. The worst kind of workaround.

Ok? Ok. Rant over. 😄

**Comment by choprahetarth** [comment]
Thanks for providing the link for the driver implementation. 

Well and I do agree with the fact that they provide very less functionality for the RVC Mode, but the TODO Was not for the sensor, my bad, as the data provided by the RVC was properly read by the program (even though the code is,.... Pretty bad :p, but then, I still am an amateur programmer). The TODO Was mainly for integrating the sensor readings with our bot using EKF or something, which I frankly don't remember as I left the project long ago. 

You can check out the functioning on the youtube video - >  https://youtu.be/F6tzxjeQdZc

**Comment by MoffKalast** [comment]
Yeah the main problem with that demo was sticking the received pitch yaw roll into a quaternion directly, as they say that's "not how any of this works", at least if you don't compensate for the wrap arounds you'll those odd jumps seen in the video.

I guess it might work if you instead gave the EKF only what you actually get from the sensor for odometry fusion, but there's also the issue that the sensor doesn't fuse mag data into the RPY angles so it's only useful as a rotational wheels slip corrector, and not very for any GNSS application. You don't get an absolute rotation, the yaw origin is the orientation you boot the sensor in. At least that's what my BNO080 unit is giving me.

**Comment by choprahetarth** [comment]
Agreed. The demo is mainly an "Acquire Data", "Convert to Quarts", "Present directly". So apparently the odd jumps are caused apparently because of this. 
Also agreed, it is FAR from reaching the level of perfection required for GNSS application, as of course, no mag data fusion for the RPY, and it's sole purpose was to correct slips on a robot, with onboard encoders and laser rangefinders. 
I don't honestly recall if the RVC mode provided absolute values, but as far as I recall, the normal acquisition method via the QUIIC system did provide an absolute orientation. 
I think referring to the datasheet can give more clarity.

**Comment by choprahetarth** [comment]
Closing this issue, since the CPP version was provided as a link
